def format_summary(summary: str) -> str:
    """Format the summary in a Telegram-friendly way with proper styling"""
    
    # Add header
    formatted_text = "<b>📝 Conversation Summary</b>\n\n"
    
    # Process the summary text
    lines = summary.split('\n')
    for line in lines:
        line = line.strip()
        if line:
            # Convert markdown-style bullets to emoji bullets
            if line.startswith('•') or line.startswith('-'):
                line = '• ' + line[1:].strip()
            elif not line.startswith('•'):
                line = '• ' + line
                
            formatted_text += f"{line}\n"
    
    # Add footer
    formatted_text += "\n<i>Generated by AI Summary Bot</i>"
    
    return formatted_text
